// Generated by scripts/sync-download-urls.mjs — do not edit by hand.
// Re-run: npm run sync:downloads
// Store config: scripts/store-urls.config.json

export const RELEASE_SOURCE_REPO = "OpenSelfHosting/OpenKey" as const

export const RELEASE_SYNC = {
  tag: "1.0.6+12",
  publishedAt: "2026-08-28T15:23:19Z",
  syncedAt: "2026-09-26T08:11:35.405Z",
} as const

/** Variant id → browser_download_url from the latest GitHub Release on OpenKey. */
export const RELEASE_ARTIFACT_URLS: Record<string, string> = {
  "windows-x64": "https://github.com/OpenSelfHosting/OpenKey/releases/download/1.0.6%2B12/OpenKey-1.0.6%2B12-windows-x64.exe",
  "macos-universal": "https://github.com/OpenSelfHosting/OpenKey/releases/download/1.0.6%2B12/OpenKey-1.0.6%2B13-macos.pkg",
  "linux-deb-x64": "https://github.com/OpenSelfHosting/OpenKey/releases/download/1.0.6%2B12/OpenKey-1.0.6%2B12-linux-x64.deb",
  "linux-appimage-x64": "https://github.com/OpenSelfHosting/OpenKey/releases/download/1.0.6%2B12/OpenKey-1.0.6%2B12-linux-x64.AppImage",
  "android-apk": "https://github.com/OpenSelfHosting/OpenKey/releases/download/1.0.6%2B12/OpenKey-1.0.6%2B12-android.apk"
}

/** Variant id → store listing URL (from scripts/store-urls.config.json). */
export const STORE_URLS: Record<string, string> = {}
