// Generated by scripts/sync-download-urls.mjs — do not edit by hand.
// Re-run: npm run sync:downloads
// Store config: scripts/store-urls.config.json

export const RELEASE_SOURCE_REPO = "OpenSelfHosting/openkey_app" as const

export const RELEASE_SYNC = {
  tag: null,
  publishedAt: null,
  syncedAt: "2026-08-10T17:17:18.578Z",
} as const

/** Variant id → browser_download_url from the latest GitHub Release on openkey_app. */
export const RELEASE_ARTIFACT_URLS: Record<string, string> = {}

/** Variant id → store listing URL (from scripts/store-urls.config.json). */
export const STORE_URLS: Record<string, string> = {}
