// Generated by scripts/sync-release-urls.mjs — do not edit by hand.
// Re-run: npm run sync:releases

export const RELEASE_SOURCE_REPO = "OpenSelfHosting/openkey_app" as const

export const RELEASE_SYNC = {
  tag: null,
  publishedAt: null,
  syncedAt: "2026-08-10T17:13:19.223Z",
} as const

/** Variant id → browser_download_url from the latest GitHub Release. */
export const RELEASE_ARTIFACT_URLS: Record<string, string> = {}
