import type { PaletteId, ThemeMode } from './useSitePrefs'

export type AppearanceCopy = {
  title: string
  subtitle: string
  theme: string
  palette: string
  font: string
  contrast: string
  contrastHint: string
  reset: string
  themes: Record<ThemeMode, { title: string; hint: string }>
  fonts: Record<string, string>
  palettes: Record<PaletteId, string>
}

const en: AppearanceCopy = {
  title: 'Customize',
  subtitle: 'Icon, theme, and font',
  theme: 'Site theme',
  palette: 'Icon theme',
  font: 'Font',
  contrast: 'High contrast',
  contrastHint: 'Stronger text and borders',
  reset: 'Reset',
  themes: {
    auto: { title: 'System', hint: 'Match device' },
    light: { title: 'Light', hint: 'Bright surface' },
    dark: { title: 'Dark', hint: 'Dim surface' },
  },
  fonts: {
    default: 'Default',
    arabic: 'Arabic',
    developer: 'Developer',
    technical: 'Technical',
    standard: 'Standard',
    figtree: 'Figtree',
    robotoFlex: 'Roboto Flex',
  },
  palettes: {
    forest: 'Forest',
    ocean: 'Ocean',
    ember: 'Ember',
    violet: 'Violet',
    slate: 'Slate',
  },
}

const copyByLang: Record<string, AppearanceCopy> = {
  en,
  ar: {
    title: 'التخصيص',
    subtitle: 'الأيقونة والسمة والخط',
    theme: 'سمة الموقع',
    palette: 'سمة الأيقونة',
    font: 'الخط',
    contrast: 'تباين عالٍ',
    contrastHint: 'نص أوضح وحدود أقوى',
    reset: 'إعادة ضبط',
    themes: {
      auto: { title: 'النظام', hint: 'يتبع الجهاز' },
      light: { title: 'فاتح', hint: 'خلفية مضيئة' },
      dark: { title: 'داكن', hint: 'خلفية داكنة' },
    },
    fonts: {
      default: 'افتراضي',
      arabic: 'عربي',
      developer: 'مطوّر',
      technical: 'تقني',
      standard: 'قياسي',
      figtree: 'Figtree',
      robotoFlex: 'Roboto Flex',
    },
    palettes: {
      forest: 'غابة',
      ocean: 'محيط',
      ember: 'جمر',
      violet: 'بنفسجي',
      slate: 'رمادي',
    },
  },
  zh: {
    ...en,
    title: '个性化',
    subtitle: '图标、主题与字体',
    theme: '网站主题',
    palette: '图标主题',
    font: '字体',
    contrast: '高对比度',
    contrastHint: '更清晰的文字与边框',
    reset: '重置',
    themes: {
      auto: { title: '跟随系统', hint: '匹配设备' },
      light: { title: '浅色', hint: '明亮背景' },
      dark: { title: '深色', hint: '暗色背景' },
    },
    fonts: {
      default: '默认',
      arabic: '阿拉伯文',
      developer: '开发者',
      technical: '技术',
      standard: '标准',
      figtree: 'Figtree',
      robotoFlex: 'Roboto Flex',
    },
    palettes: {
      forest: '森林',
      ocean: '海洋',
      ember: '余烬',
      violet: '紫罗兰',
      slate: '石板',
    },
  },
  es: {
    ...en,
    title: 'Personalizar',
    subtitle: 'Icono, tema y fuente',
    theme: 'Tema del sitio',
    palette: 'Tema del icono',
    font: 'Fuente',
    contrast: 'Alto contraste',
    contrastHint: 'Texto y bordes más marcados',
    reset: 'Restablecer',
    themes: {
      auto: { title: 'Sistema', hint: 'Seguir el dispositivo' },
      light: { title: 'Claro', hint: 'Fondo claro' },
      dark: { title: 'Oscuro', hint: 'Fondo oscuro' },
    },
    fonts: {
      default: 'Predeterminada',
      arabic: 'Árabe',
      developer: 'Desarrollador',
      technical: 'Técnica',
      standard: 'Estándar',
      figtree: 'Figtree',
      robotoFlex: 'Roboto Flex',
    },
    palettes: {
      forest: 'Bosque',
      ocean: 'Océano',
      ember: 'Brasa',
      violet: 'Violeta',
      slate: 'Pizarra',
    },
  },
  fr: {
    ...en,
    title: 'Personnaliser',
    subtitle: 'Icône, thème et police',
    theme: 'Thème du site',
    palette: 'Thème de l’icône',
    font: 'Police',
    contrast: 'Contraste élevé',
    contrastHint: 'Texte et bordures plus marqués',
    reset: 'Réinitialiser',
    themes: {
      auto: { title: 'Système', hint: 'Suivre l’appareil' },
      light: { title: 'Clair', hint: 'Fond lumineux' },
      dark: { title: 'Sombre', hint: 'Fond sombre' },
    },
    fonts: {
      default: 'Par défaut',
      arabic: 'Arabe',
      developer: 'Développeur',
      technical: 'Technique',
      standard: 'Standard',
      figtree: 'Figtree',
      robotoFlex: 'Roboto Flex',
    },
    palettes: {
      forest: 'Forêt',
      ocean: 'Océan',
      ember: 'Braise',
      violet: 'Violet',
      slate: 'Ardoise',
    },
  },
  hi: {
    ...en,
    title: 'अनुकूलन',
    subtitle: 'आइकन, थीम और फ़ॉन्ट',
    theme: 'साइट थीम',
    palette: 'आइकन थीम',
    font: 'फ़ॉन्ट',
    contrast: 'उच्च कंट्रास्ट',
    contrastHint: 'स्पष्ट टेक्स्ट और मज़बूत बॉर्डर',
    reset: 'रीसेट',
    themes: {
      auto: { title: 'सिस्टम', hint: 'डिवाइस के अनुसार' },
      light: { title: 'लाइट', hint: 'हल्की पृष्ठभूमि' },
      dark: { title: 'डार्क', hint: 'गहरी पृष्ठभूमि' },
    },
    fonts: {
      default: 'डिफ़ॉल्ट',
      arabic: 'अरबी',
      developer: 'डेवलपर',
      technical: 'तकनीकी',
      standard: 'मानक',
      figtree: 'Figtree',
      robotoFlex: 'Roboto Flex',
    },
    palettes: {
      forest: 'वन',
      ocean: 'समुद्र',
      ember: 'अंगारा',
      violet: 'बैंगनी',
      slate: 'स्लेट',
    },
  },
  bn: {
    ...en,
    title: 'কাস্টমাইজ',
    subtitle: 'আইকন, থিম ও ফন্ট',
    theme: 'সাইট থিম',
    palette: 'আইকন থিম',
    font: 'ফন্ট',
    contrast: 'উচ্চ কনট্রাস্ট',
    contrastHint: 'স্পষ্ট টেক্সট ও শক্ত বর্ডার',
    reset: 'রিসেট',
    themes: {
      auto: { title: 'সিস্টেম', hint: 'ডিভাইস অনুযায়ী' },
      light: { title: 'লাইট', hint: 'হালকা পটভূমি' },
      dark: { title: 'ডার্ক', hint: 'গাঢ় পটভূমি' },
    },
    fonts: {
      default: 'ডিফল্ট',
      arabic: 'আরবি',
      developer: 'ডেভেলপার',
      technical: 'টেকনিক্যাল',
      standard: 'স্ট্যান্ডার্ড',
      figtree: 'Figtree',
      robotoFlex: 'Roboto Flex',
    },
    palettes: {
      forest: 'বন',
      ocean: 'সমুদ্র',
      ember: 'অগ্নি',
      violet: 'বেগুনি',
      slate: 'স্লেট',
    },
  },
  pt: {
    ...en,
    title: 'Personalizar',
    subtitle: 'Ícone, tema e fonte',
    theme: 'Tema do site',
    palette: 'Tema do ícone',
    font: 'Fonte',
    contrast: 'Alto contraste',
    contrastHint: 'Texto e bordas mais fortes',
    reset: 'Redefinir',
    themes: {
      auto: { title: 'Sistema', hint: 'Seguir o dispositivo' },
      light: { title: 'Claro', hint: 'Fundo claro' },
      dark: { title: 'Escuro', hint: 'Fundo escuro' },
    },
    fonts: {
      default: 'Padrão',
      arabic: 'Árabe',
      developer: 'Desenvolvedor',
      technical: 'Técnica',
      standard: 'Padrão',
      figtree: 'Figtree',
      robotoFlex: 'Roboto Flex',
    },
    palettes: {
      forest: 'Floresta',
      ocean: 'Oceano',
      ember: 'Brasa',
      violet: 'Violeta',
      slate: 'Ardósia',
    },
  },
  ru: {
    ...en,
    title: 'Настройка',
    subtitle: 'Иконка, тема и шрифт',
    theme: 'Тема сайта',
    palette: 'Тема иконки',
    font: 'Шрифт',
    contrast: 'Высокий контраст',
    contrastHint: 'Чёткий текст и границы',
    reset: 'Сбросить',
    themes: {
      auto: { title: 'Система', hint: 'Как на устройстве' },
      light: { title: 'Светлая', hint: 'Светлый фон' },
      dark: { title: 'Тёмная', hint: 'Тёмный фон' },
    },
    fonts: {
      default: 'По умолчанию',
      arabic: 'Арабский',
      developer: 'Разработчик',
      technical: 'Технический',
      standard: 'Стандартный',
      figtree: 'Figtree',
      robotoFlex: 'Roboto Flex',
    },
    palettes: {
      forest: 'Лес',
      ocean: 'Океан',
      ember: 'Уголь',
      violet: 'Фиолетовый',
      slate: 'Сланец',
    },
  },
  ur: {
    ...en,
    title: 'تخصیص',
    subtitle: 'آئیکن، تھیم اور فونٹ',
    theme: 'سائٹ تھیم',
    palette: 'آئیکن تھیم',
    font: 'فونٹ',
    contrast: 'زیادہ کنٹراسٹ',
    contrastHint: 'واضح متن اور مضبوط بارڈر',
    reset: 'ری سیٹ',
    themes: {
      auto: { title: 'سسٹم', hint: 'ڈیوائس کے مطابق' },
      light: { title: 'لائٹ', hint: 'روشن پس منظر' },
      dark: { title: 'ڈارک', hint: 'گہرا پس منظر' },
    },
    fonts: {
      default: 'ڈیفالٹ',
      arabic: 'عربی',
      developer: 'ڈویلپر',
      technical: 'ٹیکنیکل',
      standard: 'معیاری',
      figtree: 'Figtree',
      robotoFlex: 'Roboto Flex',
    },
    palettes: {
      forest: 'جنگل',
      ocean: 'سمندر',
      ember: 'انگارہ',
      violet: 'جامنی',
      slate: 'سلیٹ',
    },
  },
}

export function appearanceCopy(lang: string): AppearanceCopy {
  return copyByLang[lang] || en
}
